## Create Numpy arrays using python list

In [7]:
import numpy as np
print(np.__version__)

1.13.3


In [9]:
l = [2,3,5,7,9]
np_array = np.array(l)
np_array

array([2, 3, 5, 7, 9])

#### Basic operation

In [11]:
l*3

[2, 3, 5, 7, 9, 2, 3, 5, 7, 9, 2, 3, 5, 7, 9]

In [12]:
np_array*3

array([ 6,  9, 15, 21, 27])

In [13]:
my_tuple = (14, -3.54, 5+7j)

In [16]:
np_array = np.array(my_tuple)
np_array

array([ 14.00+0.j,  -3.54+0.j,   5.00+7.j])

In [17]:
my_tuple*3

(14, -3.54, (5+7j), 14, -3.54, (5+7j), 14, -3.54, (5+7j))

In [18]:
np_array*3

array([ 42.00 +0.j, -10.62 +0.j,  15.00+21.j])

## Intrinsic Numpy array creation

#### ways to create

In [19]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
arr = np.arange(10,23)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [50]:
arr = np.arange(15)
arr.shape = (3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
arr = np.arange(10,23,5)
arr

array([10, 15, 20])

In [29]:
arr = np.arange(26, step=5)
arr

array([ 0,  5, 10, 15, 20, 25])

#### Finding length

In [30]:
len(arr)

6

In [31]:
arr.size

6

### Some useful functions

### linspace()

In [33]:
arr = np.linspace(5,15,9)
arr

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [34]:
arr = np.linspace(5,15, 9 , retstep = True)
arr

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [35]:
arr[1]

1.25

### zeros()

In [37]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [38]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [39]:
np.zeros((3,5,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### ones()

In [40]:
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Working with datatypes

In [41]:
np.zeros(6, dtype = 'int_')

array([0, 0, 0, 0, 0, 0])

## Boolean Mask Arrays

In [51]:
my_vector = np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [54]:
mask = (my_vector % 7) == 0
mask

array([False, False,  True, False,  True, False,  True], dtype=bool)

In [55]:
my_vector[mask]

array([  0,  21, 105])

In [57]:
my_vector[my_vector > 0]

array([  2,  21,  37, 105])