## Create Numpy arrays using python list

In [3]:
import numpy as np
print(np.__version__)

1.13.3


In [2]:
l = [2,3,5,7,9]
np_array = np.array(l)
np_array

array([2, 3, 5, 7, 9])

#### Basic operation

In [3]:
l*3

[2, 3, 5, 7, 9, 2, 3, 5, 7, 9, 2, 3, 5, 7, 9]

In [4]:
np_array*3

array([ 6,  9, 15, 21, 27])

In [5]:
my_tuple = (14, -3.54, 5+7j)

In [6]:
np_array = np.array(my_tuple)
np_array

array([ 14.00+0.j,  -3.54+0.j,   5.00+7.j])

In [7]:
my_tuple*3

(14, -3.54, (5+7j), 14, -3.54, (5+7j), 14, -3.54, (5+7j))

In [8]:
np_array*3

array([ 42.00 +0.j, -10.62 +0.j,  15.00+21.j])

## Intrinsic Numpy array creation

#### ways to create

In [9]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
arr = np.arange(10,23)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [11]:
arr = np.arange(15)
arr.shape = (3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr = np.arange(10,23,5)
arr

array([10, 15, 20])

In [13]:
arr = np.arange(26, step=5)
arr

array([ 0,  5, 10, 15, 20, 25])

#### Finding length

In [14]:
len(arr)

6

In [15]:
arr.size

6

### Some useful functions

### linspace()

In [16]:
arr = np.linspace(5,15,9)
arr

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [17]:
arr = np.linspace(5,15, 9 , retstep = True)
arr

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [18]:
arr[1]

1.25

### zeros()

In [19]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.zeros((3,5,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### ones()

In [22]:
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### eye() method - identity matrix

In [4]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [7]:
arr = np.random.randint(1,25,6)
arr

array([10,  1, 24,  1, 14, 16])

In [9]:
# min()
arr.min()

1

In [10]:
# max()
arr.max()

24

In [11]:
# argmax()
arr.argmax()

2

In [13]:
arr.shape

(6,)

In [14]:
arr.dtype

dtype('int32')

### Working with datatypes

In [23]:
np.zeros(6, dtype = 'int_')

array([0, 0, 0, 0, 0, 0])

## Boolean Mask Arrays

In [24]:
my_vector = np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [25]:
mask = (my_vector % 7) == 0
mask

array([False, False,  True, False,  True, False,  True], dtype=bool)

In [26]:
my_vector[mask]

array([  0,  21, 105])

In [27]:
my_vector[my_vector > 0]

array([  2,  21,  37, 105])

## [Broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

In [15]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[2:5] = 100
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
my_3d_array = np.arange(70).reshape(2,7,5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [32]:
#shape
my_3d_array.shape

(2, 7, 5)

In [34]:
#number of dimensions
my_3d_array.ndim

3

In [35]:
#size
my_3d_array.size

70

In [37]:
#data type of each element
my_3d_array.dtype

dtype('int32')

In [38]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))
print(left_mat)
print(right_mat)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [39]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [40]:
my_3d_array.shape

(2, 7, 5)

In [41]:
my_3d_array.sum()

2415

In [42]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [43]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [44]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [46]:
matrix = np.ones(35, dtype='int_').reshape((7,5)) * 3
matrix

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [49]:
random_matrix = np.random.random((7,5))
random_matrix

array([[ 0.39707094,  0.98275159,  0.85723912,  0.54545543,  0.97880239],
       [ 0.99317898,  0.70486473,  0.97081316,  0.8061478 ,  0.65807468],
       [ 0.40343277,  0.15814961,  0.67557168,  0.18882999,  0.66311184],
       [ 0.5028883 ,  0.12707657,  0.68198419,  0.22181486,  0.21385105],
       [ 0.2878566 ,  0.61222454,  0.96589077,  0.1459949 ,  0.90912026],
       [ 0.71835512,  0.78733088,  0.14040382,  0.36532672,  0.17395924],
       [ 0.55299296,  0.17400905,  0.1153165 ,  0.12755473,  0.45814576]])

In [51]:
np.set_printoptions(precision=4)
my_3d_array * random_matrix

array([[[  0.    ,   0.9828,   1.7145,   1.6364,   3.9152],
        [  4.9659,   4.2292,   6.7957,   6.4492,   5.9227],
        [  4.0343,   1.7396,   8.1069,   2.4548,   9.2836],
        [  7.5433,   2.0332,  11.5937,   3.9927,   4.0632],
        [  5.7571,  12.8567,  21.2496,   3.3579,  21.8189],
        [ 17.9589,  20.4706,   3.7909,  10.2291,   5.0448],
        [ 16.5898,   5.3943,   3.6901,   4.2093,  15.577 ]],

       [[ 13.8975,  35.3791,  31.7178,  20.7273,  38.1733],
        [ 39.7272,  28.8995,  40.7742,  34.6644,  28.9553],
        [ 18.1545,   7.2749,  31.7519,   9.0638,  32.4925],
        [ 25.1444,   6.4809,  35.4632,  11.7562,  11.548 ],
        [ 15.8321,  34.2846,  55.0558,   8.4677,  53.6381],
        [ 43.1013,  48.0272,   8.705 ,  23.0156,  11.1334],
        [ 35.9445,  11.4846,   7.7262,   8.6737,  31.6121]]])

## [Creating Structured Arrays](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.rec.html)

In [54]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'),('age','i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [56]:
people_array = np.zeros((4), dtype=person_data_def)
people_array

array([(b'',  0.,  0., 0), (b'',  0.,  0., 0), (b'',  0.,  0., 0),
       (b'',  0.,  0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [57]:
people_array[3] = ('Delta',73,205,34)
people_array[0] = ('Alpha',65,112,23)

In [58]:
people_array


array([(b'Alpha',  65.,  112., 23), (b'',   0.,    0.,  0),
       (b'',   0.,    0.,  0), (b'Delta',  73.,  205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [60]:
people_array['age']

array([23,  0,  0, 34], dtype=int64)

## Multi-dimentional Structured Arrays

In [62]:
people_big_array = np.zeros((4,3,2), dtype = person_data_def)
people_big_array

array([[[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [63]:
people_big_array[3,2,1] = ('Echo',68,155,46)
people_big_array

array([[[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'Echo',  68.,  155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [64]:
people_big_array['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,  68.]]])

In [66]:
people_big_array[['height','weight']]

array([[[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), ( 68.,  155.)]]],
      dtype=[('height', '<f8'), ('weight', '<f8')])